name: geopandas
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab
  - jupyter-book
  - matplotlib
  - numpy
  - pip
  - pandas
  - python=3.9
  - scikit-learn
  - pip:
    - geopandas
    - contextily
    - libpysal
    - mapclassify
    - pycodestyle
    - pycodestyle_magic
    - flake8
    
